steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tugas6-be", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tugas6-be"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "run",
        "deploy",
        "backend-service",
        "--image",
        "gcr.io/$PROJECT_ID/tugas6-be",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
